v1.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -837,8 +837,14 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
+  --enable-debug          enable extra debug messages at compile-time
   --enable-fhs            force FHS-compliant directories, ignoring --prefix
                           etc
+
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-workshop         use Sun WorkShop 'CC -xar' as the 'ar' tool
 
 Some influential environment variables:
   CC          C compiler command
@@ -1453,7 +1459,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=emailrelay
- VERSION=1.0.2
+ VERSION=1.1
 
 
 cat >>confdefs.h <<_ACEOF
@@ -3269,6 +3275,10 @@ fi
 
 
 	COMPILER_VERSION=`$CXX --version 2>/dev/null | sed q | sed 's/[^0-9 .]*//g;s/\./ /g;s/^ *//;s/ /./;s/ .*//;s/^/gcc/'`
+	if test -z "${COMPILER_VERSION}"
+	then
+		COMPILER_VERSION=`$CXX -V 2>&1 | sed q | grep WorkShop | sed 's/[^0-9]*//;s/[ \.].*//;s/^/sunpro/'`
+	fi
 
 
 
@@ -4611,6 +4621,68 @@ _ACEOF
 
   fi
 
+echo "$as_me:$LINENO: checking for buggy ctime" >&5
+echo $ECHO_N "checking for buggy ctime... $ECHO_C" >&6
+if test "${aclocal_cv_buggy_ctime+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <ctime>
+#include <unistd.h>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  aclocal_cv_buggy_ctime=no
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+aclocal_cv_buggy_ctime=yes
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+fi
+echo "$as_me:$LINENO: result: $aclocal_cv_buggy_ctime" >&5
+echo "${ECHO_T}$aclocal_cv_buggy_ctime" >&6
+	if test $aclocal_cv_buggy_ctime = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BUGGY_CTIME 1
+_ACEOF
+
+	else
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_BUGGY_CTIME 0
+_ACEOF
+
+	fi
+
 echo "$as_me:$LINENO: checking for gmtime_r" >&5
 echo $ECHO_N "checking for gmtime_r... $ECHO_C" >&6
 if test "${aclocal_cv_gmtime_r+set}" = set; then
@@ -4734,6 +4806,37 @@ _ACEOF
 	fi
 
 
+# Check whether --enable-debug or --disable-debug was given.
+if test "${enable_debug+set}" = set; then
+  enableval="$enable_debug"
+
+fi;
+
+if test "$enable_debug" = "yes"
+then
+
+cat >>confdefs.h <<\_ACEOF
+#define _DEBUG 1
+_ACEOF
+
+fi
+
+
+
+# Check whether --with-workshop or --without-workshop was given.
+if test "${with_workshop+set}" = set; then
+  withval="$with_workshop"
+
+fi;
+
+if test "$with_workshop" = "yes"
+then
+	chmod +x lib/sunpro5/xar
+	AR="`pwd`/lib/sunpro5/xar --cxx \"$CXX\""
+
+fi
+
+
 # Check whether --enable-fhs or --disable-fhs was given.
 if test "${enable_fhs+set}" = set; then
   enableval="$enable_fhs"
@@ -4791,7 +4894,7 @@ fi
 
 SET_MAKE=""
 
-ac_config_files="$ac_config_files Makefile src/Makefile src/glib/Makefile src/gnet/Makefile src/gsmtp/Makefile src/main/Makefile src/win32/Makefile lib/Makefile lib/gcc2.95/Makefile lib/msvc6.0/Makefile bin/Makefile doc/Makefile"
+ac_config_files="$ac_config_files Makefile src/Makefile src/glib/Makefile src/gnet/Makefile src/gsmtp/Makefile src/main/Makefile src/win32/Makefile lib/Makefile lib/gcc2.95/Makefile lib/msvc6.0/Makefile lib/sunpro5/Makefile bin/Makefile doc/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -5290,6 +5393,7 @@ do
   "lib/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/Makefile" ;;
   "lib/gcc2.95/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/gcc2.95/Makefile" ;;
   "lib/msvc6.0/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/msvc6.0/Makefile" ;;
+  "lib/sunpro5/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/sunpro5/Makefile" ;;
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
